FROM golang:1 as builder

WORKDIR /go/src/app

COPY go.* ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o app ./cmd/sender

FROM alpine:latest
COPY --from=builder /go/src/app .
CMD ["./app"]
