apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: golang-sample
  name: golang-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golang-sample
    spec:
      containers:
      - image: minikube-golang-sample
        name: golang-sample
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 8080
status: {}