apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: google-cloud-sample
  name: google-cloud-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: google-cloud-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: google-cloud-sample
    spec:
      containers:
      - image: google-cloud-sample
        name: google-cloud-sample
        resources: {}
        ports:
          - containerPort: 8080
status: {}